export type StepType='learn'|'multiple-choice'|'true-false'|'vocabulary'|'fill-blank'|'apply';
export type LessonStep={id:string;type:StepType;title:string;content:string;options?:string[];correctAnswer?:string;explanation?:string;xp?:number};
export type Lesson={id:string;unit:string;title:string;icon:string;description:string;steps:LessonStep[]};
const lesson=(id:string,unit:string,title:string,icon:string,description:string,content:string,question:string,options:string[],correctAnswer:string,apply:string):Lesson=>({id,unit,title,icon,description,steps:[{id:'learn',type:'learn',title,content},{id:'check',type:'multiple-choice',title:question,content:'Choose the best answer.',options,correctAnswer,explanation:'Look for the choice that is accurate, specific, and responsible.',xp:10},{id:'apply',type:'apply',title:'Put it to work',content:apply,xp:20}]});
export const lessons:Lesson[]=[
lesson('what-is-ai','AI Foundations','What Is AI?','🧠','Discover how AI finds patterns.','Artificial intelligence is technology that recognizes patterns, makes predictions, and helps solve problems.','AI is best described as…',['A robot with a brain','Technology that finds patterns in data','A search engine'],'Technology that finds patterns in data','Name an AI tool you use and describe what it helps you do.'),
lesson('machine-learning','AI Foundations','Machine Learning','💡','How systems learn from examples.','Machine learning trains models on examples so they can make useful guesses about new examples.','What does a dataset provide?',['Training examples','Internet access','A personality'],'Training examples','Describe data you would collect to teach an AI to identify a healthy plant.'),
lesson('how-ai-learns','AI Foundations','How AI Learns','⚙️','Training, testing, and feedback.','During training, a model adjusts based on lots of examples and feedback. Testing checks whether it works with new data.','Why do we test a model?',['To see if it works on new data','To make it bigger','To give it a name'],'To see if it works on new data','Explain why testing on new examples matters.'),
lesson('generative-ai','AI Foundations','Generative AI','✨','Create with care and intention.','Generative AI creates new text, images, audio, or code by predicting patterns from its training data.','Which is a strong prompt?',['Write about climate change.','Explain three climate effects for grade 10 in five bullet points.','Help me.'],'Explain three climate effects for grade 10 in five bullet points.','Improve “Help me with my essay” by adding topic, audience, and format.'),
lesson('algorithms','AI Lingo','Algorithms','🔮','Recipes behind decisions.','An algorithm is a step-by-step set of instructions for solving a problem.','An algorithm is most like…',['A recipe','A battery','A screen'],'A recipe','Give directions for a simple task as a numbered algorithm.'),
lesson('models','AI Lingo','Models','🧩','Pattern-finding systems.','A model is a system trained to recognize patterns and generate outputs from data.','A model learns from…',['Examples in data','Only one answer','Luck'],'Examples in data','Explain what a music recommendation model might learn from.'),
lesson('data','AI Lingo','Data','📊','The fuel for AI.','Data is information collected as examples, measurements, images, text, or other records.','Good AI data should be…',['Relevant and representative','Secret by default','Only numbers'],'Relevant and representative','Describe one bias that could appear in a school survey dataset.'),
lesson('prompts','AI Lingo','Prompts','💬','Clear instructions create better work.','A prompt is the instruction or input you give an AI system. Context, constraints, and a desired format improve it.','Which prompt gives useful constraints?',['Help with biology.','Summarize photosynthesis for grade 9 in four bullets.','Tell me stuff.'],'Summarize photosynthesis for grade 9 in four bullets.','Write a precise prompt to create a short study guide.'),
lesson('tokens','AI Lingo','Tokens','🔤','The pieces AI reads.','Tokens are small pieces of text that AI systems process. They can be words, parts of words, or punctuation.','Why do tokens matter?',['They affect how much context a model can process','They make AI conscious','They are passwords'],'They affect how much context a model can process','Explain why a very long prompt may be difficult for a model.'),
lesson('prompt-engineering','Using AI','Prompt Engineering','✍️','Design better instructions.','Prompt engineering means deliberately structuring instructions so an AI can produce a useful, appropriate response.','What should a research prompt include?',['Task, context, and format','Only “do it”','A fake source'],'Task, context, and format','Write a research prompt that asks for sources to be labeled clearly.'),
lesson('ai-for-studying','Using AI','AI for Studying','📚','Learn with AI, not from it.','AI can help you brainstorm, quiz yourself, explain concepts, and make study plans. It should not replace your thinking.','A responsible study use is…',['Asking for a practice quiz','Submitting AI work as yours','Skipping all sources'],'Asking for a practice quiz','Describe a way you could check your understanding after using AI.'),
lesson('ai-for-research','Using AI','AI for Research','🔎','Research critically.','AI can help plan research, but important claims must be verified against credible original sources.','Before using an AI claim, you should…',['Verify it with a credible source','Assume it is cited','Make it sound confident'],'Verify it with a credible source','Write a checklist for verifying an AI-provided statistic.'),
lesson('fact-checking','Using AI','Fact-Checking','✅','Verify before you share.','Fact-checking compares a claim with reliable, relevant evidence and considers the source, date, and context.','The strongest source for a scientific claim is often…',['The original study or expert institution','A random comment','An AI summary alone'],'The original study or expert institution','Describe how you would check a surprising statistic.'),
lesson('bias','Responsible AI','Bias','⚖️','Spot unfair patterns.','Bias is a systematic unfair pattern in data, design, or decisions that can lead to unequal outcomes.','Bias can happen when training data is…',['Missing important groups','Carefully reviewed','Clearly labeled'],'Missing important groups','Give an example of how a biased dataset could cause harm.'),
lesson('hallucinations','Responsible AI','Hallucinations','🌫️','When confident answers are wrong.','A hallucination is information generated by AI that sounds convincing but is incorrect or fabricated.','A possible hallucination is…',['A made-up citation','A linked primary source','A math answer you check'],'A made-up citation','Explain what you should do when an AI gives an unfamiliar citation.'),
lesson('privacy','Responsible AI','Privacy','🔐','Keep personal information safe.','Privacy means controlling personal information and understanding how data may be collected, used, and shared.','Never paste this into a public AI tool:',['A password or private student record','A public poem','A made-up example'],'A password or private student record','List two ways to protect private information when using AI.'),
lesson('copyright','Responsible AI','Copyright','©️','Respect creative work.','Copyright protects original creative work. Using AI does not remove your responsibility to cite, transform, and follow rules.','A responsible choice is to…',['Cite sources and follow your school rules','Claim all AI work is yours','Copy an artist’s work exactly'],'Cite sources and follow your school rules','Explain how you would credit help received from AI and sources.'),
lesson('academic-integrity','Responsible AI','Academic Integrity','🎓','Own your learning.','Academic integrity means doing honest work, acknowledging help, and following expectations for your class.','AI is appropriate when you…',['Use it within your teacher’s rules and acknowledge help','Use it secretly for every answer','Let it take your test'],'Use it within your teacher’s rules and acknowledge help','Describe a transparent way to use AI on an assignment.')
];
export type Vocab={id:string;term:string;definition:string;example:string;category:string};
export const vocabulary:Vocab[]=[
['artificial-intelligence','Artificial Intelligence','Technology that performs tasks involving patterns, predictions, or decisions.','A spam filter uses AI to flag suspicious email.','Fundamentals'],['machine-learning','Machine Learning','A way for systems to learn patterns from examples.','A model learns to recognize plant diseases from photos.','Fundamentals'],['algorithm','Algorithm','A sequence of instructions for solving a problem.','A recipe is an everyday algorithm.','Fundamentals'],['model','Model','A trained system that maps inputs to outputs.','A model suggests the next word in a sentence.','Fundamentals'],['dataset','Dataset','A collection of examples used to train or evaluate AI.','A dataset may contain labeled photos of birds.','Data'],['training-data','Training Data','Examples used while teaching a model patterns.','Training data helps a model identify shapes.','Data'],['inference','Inference','Using a trained model to produce an output or prediction.','The model makes an inference about a photo.','Fundamentals'],['generative-ai','Generative AI','AI that creates new text, images, audio, or code.','A tool drafts a poem from your prompt.','Creation'],['prompt','Prompt','The instruction or input given to an AI system.','“Explain gravity in three bullets” is a prompt.','Creation'],['token','Token','A small unit of text that a language model processes.','A word can be one or more tokens.','Technical'],['context-window','Context Window','The amount of information a model can consider at one time.','A long chat can exceed a model’s context window.','Technical'],['fine-tuning','Fine-tuning','Additional training that adapts a model to a specific task.','A general model is fine-tuned for medical language.','Technical'],['hallucination','Hallucination','A confident-sounding AI output that is false or invented.','The AI invents a book that does not exist.','Safety'],['bias','Bias','An unfair pattern that can affect AI outputs or decisions.','A hiring model performs poorly for an underrepresented group.','Safety'],['deep-learning','Deep Learning','Machine learning that uses multi-layer neural networks.','Deep learning can recognize complex visual patterns.','Technical'],['neural-network','Neural Network','A layered model inspired loosely by connected neurons.','A neural network learns patterns in images.','Technical'],['ai-agent','AI Agent','An AI system that can plan and act toward a goal.','An agent organizes steps for a travel plan.','Tools'],['multimodal-ai','Multimodal AI','AI that works across text, images, audio, or video.','A model answers questions about an uploaded image.','Tools'],['embedding','Embedding','A numerical representation that captures relationships in data.','Similar sentences have nearby embeddings.','Technical'],['computer-vision','Computer Vision','AI that interprets images and video.','A vision system identifies objects in a photo.','Tools']
].map(([id,term,definition,example,category])=>({id,term,definition,example,category}));
export type ResearchArticle={id:string;category:string;title:string;summary:string;body:string;takeaways:string[];source:{label:string;url:string}};
export const research:ResearchArticle[]=[
{id:'fundamentals',category:'AI Fundamentals',title:'How AI systems learn from examples',summary:'A primer on patterns, models, and careful evaluation.',body:'Most modern AI systems learn statistical patterns from data. That makes them useful for narrow tasks, but it does not make their outputs automatically true or fair.',takeaways:['Models need relevant evaluation data.','Outputs are predictions, not facts.'],source:{label:'Stanford AI Index Report',url:'https://aiindex.stanford.edu/report/'}},
{id:'generative',category:'Generative AI',title:'Creating responsibly with generative AI',summary:'What generative systems create and why verification still matters.',body:'Generative systems can draft content quickly. Students should treat outputs as a starting point, verify claims, and follow class expectations for disclosure and citation.',takeaways:['Ask for sources, then verify them.','Keep your own thinking in the loop.'],source:{label:'NIST AI Risk Management Framework',url:'https://www.nist.gov/itl/ai-risk-management-framework'}},
{id:'education',category:'AI in Education',title:'AI as a learning partner',summary:'Using AI to support—not replace—student learning.',body:'AI can assist with explanations, practice questions, and feedback. Its best educational use strengthens student agency, critical thinking, and teacher-guided learning.',takeaways:['Use AI to practice, not to bypass learning.','Check school policies.'],source:{label:'U.S. Department of Education',url:'https://tech.ed.gov/ai/'}},
{id:'tools',category:'AI Tools',title:'Choosing an AI tool thoughtfully',summary:'Different tools have different strengths, risks, and privacy terms.',body:'Before using a tool, consider its purpose, accuracy limits, privacy policy, and whether it cites sources. A tool’s confidence is not evidence.',takeaways:['Match the tool to the task.','Avoid sharing sensitive data.'],source:{label:'NIST AI RMF',url:'https://www.nist.gov/itl/ai-risk-management-framework'}},
{id:'ethics',category:'AI Ethics',title:'The human questions behind AI',summary:'Fairness, transparency, safety, and accountability.',body:'AI systems affect people differently. Ethical use asks who benefits, who could be harmed, what data was used, and who is accountable for a decision.',takeaways:['Look for unequal impacts.','Humans remain responsible for decisions.'],source:{label:'UNESCO Recommendation on the Ethics of AI',url:'https://www.unesco.org/en/artificial-intelligence/recommendation-ethics'}},
{id:'society',category:'AI & Society',title:'AI literacy is civic literacy',summary:'Why everyone needs tools to understand AI’s role in society.',body:'AI affects media, school, work, and public services. AI literacy helps people evaluate claims, protect privacy, and participate in decisions about technology.',takeaways:['Question automated outputs.','Participate in conversations about AI policy.'],source:{label:'Stanford AI Index Report',url:'https://aiindex.stanford.edu/report/'}}
];
export const challengeQuestions=[
{id:'prompt',category:'tools',question:'You need help studying a chapter. Which prompt is most useful?',options:['Explain it.','Make a five-question grade-10 quiz on cell division and include answer explanations.','Do my homework.'],answer:1},
{id:'research',category:'thinking',question:'AI gives you a statistic with no link. What should you do?',options:['Use it if it sounds confident.','Verify it using a credible original source.','Ask AI to make it longer.'],answer:1},
{id:'hallucination',category:'knowledge',question:'An AI cites a book you cannot find. This is most likely a…',options:['Token','Hallucination','Fine-tuning'],answer:1},
{id:'bias',category:'ethics',question:'A face-recognition model works worse for one population. What issue should be investigated?',options:['Bias in data or evaluation','The font used in the app','Whether it has enough emojis'],answer:0},
{id:'integrity',category:'ethics',question:'Your school permits AI brainstorming with disclosure. What is responsible?',options:['Submit its draft unchanged.','Use ideas, write your own work, and acknowledge the tool.','Hide all AI use.'],answer:1},
{id:'privacy',category:'tools',question:'What should not be pasted into a public AI chatbot?',options:['A made-up practice scenario','A password and private student record','A public-domain poem'],answer:1}
];
