'use client';
import {createContext,useContext,useEffect,useMemo,useState} from 'react';
import {lessons} from './data';
export type StudentState={xp:number;streak:number;hearts:number;maxHearts:number;completedLessons:string[];currentLessonId:string|null;learnedVocabulary:string[];unlockedBadges:string[];completedChallenges:number;dailyGoalMinutes:number;dailyProgressMinutes:number;lastActiveDate:string|null;activityDates:string[];finalChallengeCompleted:boolean;awardedRewards:string[]};
export const initialStudent:StudentState={xp:0,streak:0,hearts:5,maxHearts:5,completedLessons:[],currentLessonId:null,learnedVocabulary:[],unlockedBadges:[],completedChallenges:0,dailyGoalMinutes:10,dailyProgressMinutes:0,lastActiveDate:null,activityDates:[],finalChallengeCompleted:false,awardedRewards:[]};
const STORAGE_KEY='ai-lingo-state'; const dateKey=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}; const daysBetween=(a:string,b:string)=>Math.round((Date.parse(b+'T00:00:00')-Date.parse(a+'T00:00:00'))/86400000);
export const levelFor=(xp:number)=>{const levels=[{level:1,title:'AI Curious',min:0,next:500},{level:2,title:'AI Explorer',min:500,next:1000},{level:3,title:'AI Thinker',min:1000,next:2000},{level:4,title:'AI Practitioner',min:2000,next:3500},{level:5,title:'AI Fluent',min:3500,next:null}];return levels.slice().reverse().find(x=>xp>=x.min)!};
const badgesFor=(s:StudentState)=>{const ids:string[]=[];if(lessons.slice(0,4).every(l=>s.completedLessons.includes(l.id)))ids.push('beginner');if(s.learnedVocabulary.length>=10)ids.push('lingo');if(s.completedLessons.includes('prompt-engineering'))ids.push('prompt');if(s.completedLessons.includes('fact-checking')&&s.completedLessons.includes('hallucinations'))ids.push('fact');if(lessons.filter(l=>l.unit==='Responsible AI').every(l=>s.completedLessons.includes(l.id)))ids.push('guardian');if(s.finalChallengeCompleted)ids.push('fluent');return ids};
type API={student:StudentState;level:ReturnType<typeof levelFor>;isUnlocked:(id:string)=>boolean;award:(key:string,xp:number,minutes?:number)=>boolean;answer:(lessonId:string,stepId:string,correct:boolean,xp:number)=>boolean;completeLesson:(id:string,perfect:boolean)=>number;learnTerm:(id:string)=>boolean;completeChallenge:(passed:boolean)=>boolean;restoreHearts:()=>void;reset:()=>void}; const C=createContext<API|null>(null);
function parsed(value:string|null){if(!value)return initialStudent;try{const raw=JSON.parse(value);if(!raw||typeof raw!=='object')return initialStudent;return {...initialStudent,...raw,completedLessons:Array.isArray(raw.completedLessons)?raw.completedLessons:[],learnedVocabulary:Array.isArray(raw.learnedVocabulary)?raw.learnedVocabulary:[],unlockedBadges:Array.isArray(raw.unlockedBadges)?raw.unlockedBadges:[],awardedRewards:Array.isArray(raw.awardedRewards)?raw.awardedRewards:[],activityDates:Array.isArray(raw.activityDates)?raw.activityDates:[]}}catch{return initialStudent}}
export function StudentProvider({children}:{children:React.ReactNode}){const [student,setStudent]=useState(initialStudent);const [hydrated,setHydrated]=useState(false);useEffect(()=>{setStudent(parsed(localStorage.getItem(STORAGE_KEY)));setHydrated(true)},[]);useEffect(()=>{if(hydrated)localStorage.setItem(STORAGE_KEY,JSON.stringify(student))},[student,hydrated]);const updateActivity=(s:StudentState,minutes=0)=>{const today=dateKey();let streak=s.streak;let daily=s.lastActiveDate===today?s.dailyProgressMinutes:0;if(s.lastActiveDate!==today){streak=!s.lastActiveDate?1:daysBetween(s.lastActiveDate,today)===1?s.streak+1:1}const wasGoal=daily>=s.dailyGoalMinutes;daily+=minutes;let xp=0,awarded=s.awardedRewards;if(!wasGoal&&daily>=s.dailyGoalMinutes&&!awarded.includes('daily:'+today)){xp=50;awarded=[...awarded,'daily:'+today]}return {...s,lastActiveDate:today,streak,dailyProgressMinutes:daily,activityDates:s.activityDates.includes(today)?s.activityDates:[...s.activityDates,today],awardedRewards:awarded,xp:s.xp+xp}};
const api:API=useMemo(()=>({student,level:levelFor(student.xp),isUnlocked:(id)=>{const index=lessons.findIndex(l=>l.id===id);return index===0||index>0&&student.completedLessons.includes(lessons[index-1].id)},award:(key,xp,minutes=1)=>{let granted=false;setStudent(s=>{if(s.awardedRewards.includes(key))return updateActivity(s,minutes);granted=true;let next=updateActivity({...s,xp:s.xp+xp,awardedRewards:[...s.awardedRewards,key]},minutes);return {...next,unlockedBadges:badgesFor(next)} });return granted},answer:(lessonId,stepId,correct,xp)=>{let granted=false;setStudent(s=>{let next=updateActivity(s,1);if(correct){const key=`answer:${lessonId}:${stepId}`;if(!next.awardedRewards.includes(key)){granted=true;next={...next,xp:next.xp+xp,awardedRewards:[...next.awardedRewards,key]}}}else next={...next,hearts:Math.max(0,next.hearts-1)};return {...next,unlockedBadges:badgesFor(next)}});return granted},completeLesson:(id,perfect)=>{let gained=0;setStudent(s=>{if(s.completedLessons.includes(id))return updateActivity(s,2);let next=updateActivity({...s,completedLessons:[...s.completedLessons,id],currentLessonId:null,xp:s.xp+50,awardedRewards:[...s.awardedRewards,`complete:${id}`]},2);gained=50;if(perfect&&!next.awardedRewards.includes(`perfect:${id}`)){next={...next,xp:next.xp+25,awardedRewards:[...next.awardedRewards,`perfect:${id}`]};gained+=25}return {...next,unlockedBadges:badgesFor(next)}});return gained},learnTerm:(id)=>{let granted=false;setStudent(s=>{if(s.learnedVocabulary.includes(id))return updateActivity(s,1);granted=true;const next=updateActivity({...s,learnedVocabulary:[...s.learnedVocabulary,id],xp:s.xp+20,awardedRewards:[...s.awardedRewards,`vocab:${id}`]},1);return {...next,unlockedBadges:badgesFor(next)}});return granted},completeChallenge:(passed)=>{let granted=false;setStudent(s=>{if(s.finalChallengeCompleted)return s;granted=true;const next=updateActivity({...s,finalChallengeCompleted:passed,completedChallenges:s.completedChallenges+1,xp:s.xp+(passed?100:0),awardedRewards:[...s.awardedRewards,'challenge:final']},4);return {...next,unlockedBadges:badgesFor(next)}});return granted},restoreHearts:()=>setStudent(s=>({...s,hearts:s.maxHearts})),reset:()=>setStudent(initialStudent)}),[student]);return <C.Provider value={api}>{children}</C.Provider>}; export const useStudent=()=>{const x=useContext(C);if(!x)throw Error('StudentProvider missing');return x}; export {badgesFor};
